version: '3.8'

services:
  backend:
    build: ./backend
    container_name: parking-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/database.sqlite:/app/database.sqlite
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    restart: always

  redis:
    # 🚀 换用 DaoCloud 企业级极其稳定的源
    image: docker.m.daocloud.io/library/redis:7-alpine
    container_name: parking-redis
    ports:
      - "6379:6379"
    restart: always